version: "3.7"

services:
  diplomaBack:
    container_name: fjd-7-diploma-back
    image: fjd-7-diploma-back
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "$PWD/storage:/storage"
    environment:
      SERVICE_PORT: 8080
      FILE_STORAGE: /storage
      DATABASE_URL: jdbc:postgresql://diplomaPostgres:5432/postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 12345
    ports:
      - 8080:8080
    depends_on:
      - diplomaPostgres

  diplomaPostgres:
    container_name: fjd-7-diploma-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - 5432:5432

  diplomaFront:
    container_name: fjd-7-diploma-front
    image: fjd-7-diploma-front
    build:
      context: .
      dockerfile: Dockerfile.front
      args:
        BACKEND_URL: http://localhost:8080
    ports:
      - 80:80
    depends_on:
      - diplomaBack
